# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'zmlg' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DuoBao
    pod 'MBProgressHUD', '~> 0.8'
    pod 'AFNetworking', '~> 3.1.0'
#    pod 'Meiqia', '~> 3.1.9'
    pod 'ReactiveCocoa','2.1.8'
    pod 'LKDBHelper', '~>2.1.8'
    pod 'TKAlert&TKActionSheet', '~> 1.0.23'
    pod 'SIAlertView', '~> 1.3'
#    pod 'Colours', '~> 5.13.0'
    pod 'UIImage+Additions', '~> 2.1.0'
    pod 'DLAlertView', '~> 1.2.5'
    pod 'LDProgressView', '~> 1.2.1'
#    pod 'YYKit', '~> 1.0.5'
    pod 'TYAlertController', '~> 1.1.3'
    pod 'JMJParametricAnimation', '~> 1.0'
    pod 'ButtonAppearance', '~> 0.1.1'
#    pod 'YPTabBarController', '~> 1.1.6'
    pod 'SDiPhoneVersion', '~> 1.1.2'
    pod 'Masonry', '~> 1.0.0'
#    pod 'QRCodeReaderViewController', '~> 4.0.1'
#    pod 'ShareSDK3', '~> 3.2.5'
    pod 'JDFlipNumberView', '~> 2.2.3'
#    pod 'STKWebKitViewController', '~> 0.5.0'
#    pod 'EdgeAnimateView-iOS', '~> 1.0.2'
    pod 'Google/Analytics'
    pod 'JPush', '~> 2.1.6'
#    pod 'Reachability', '~> 3.2'
    pod 'BTBadgeView', '~> 1.3'
    pod 'MZTimerLabel', '~> 0.5.4'
    pod 'SDWebImage', '~> 3.7.6'


  target 'DuoBaoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DuoBaoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'lgdb' do
    pod 'MBProgressHUD', '~> 0.8'
    pod 'AFNetworking', '~> 3.1.0'
    #    pod 'Meiqia', '~> 3.1.9'
    pod 'ReactiveCocoa','2.1.8'
    pod 'LKDBHelper', '~>2.1.8'
    pod 'TKAlert&TKActionSheet', '~> 1.0.23'
    pod 'SIAlertView', '~> 1.3'
    #    pod 'Colours', '~> 5.13.0'
    pod 'UIImage+Additions', '~> 2.1.0'
    pod 'DLAlertView', '~> 1.2.5'
    pod 'LDProgressView', '~> 1.2.1'
    #    pod 'YYKit', '~> 1.0.5'
    pod 'TYAlertController', '~> 1.1.3'
    pod 'JMJParametricAnimation', '~> 1.0'
    pod 'ButtonAppearance', '~> 0.1.1'
    #    pod 'YPTabBarController', '~> 1.1.6'
    pod 'SDiPhoneVersion', '~> 1.1.2'
    pod 'Masonry', '~> 1.0.0'
    #    pod 'QRCodeReaderViewController', '~> 4.0.1'
    #    pod 'ShareSDK3', '~> 3.2.5'
    pod 'JDFlipNumberView', '~> 2.2.3'
    #    pod 'STKWebKitViewController', '~> 0.5.0'
    #    pod 'EdgeAnimateView-iOS', '~> 1.0.2'
    pod 'Google/Analytics'
    pod 'JPush', '~> 2.1.6'
    #    pod 'Reachability', '~> 3.2'
    pod 'BTBadgeView', '~> 1.3'
    pod 'MZTimerLabel', '~> 0.5.4'


end
